GET http://localhost:8080/api/users/60fd627960d5a82050c00658
###
GET http://localhost:8080/api/users/
###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "username":"jaja",
    "password":"khikhi"

}
###
PUT http://localhost:8080/api/users/60fd627960d5a82050c00658
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmQ2Mjc5NjBkNWE4MjA1MGMwMDY1OCIsImlhdCI6MTYyNzIzMzk3Mn0.SqMbeIXVdAFbuUr7eGV5DhycpOpb741ilt0cAmbzma8


{
    "data":{
        "password":"1234567"
    }
    
}
###
DELETE http://localhost:8080/api/users/60fd5128c7389809f0376acd
###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username":"jaja",
    "password":"1234567"
}

###
